import { add } from 'date-fns';
import { WycieczkaData } from "./wycieczkaData"

export const Wycieczki: WycieczkaData[] = [
    {
        id : 0,
        name: 'Podróż po Polsce',
        country: 'Polska',
        // startdate: new Date(2021, 2, 1,1,1,1,1},
        startDate: add(new Date(), { months: 2 }),
        endDate: add(new Date(), { months: 3 }),
        description: 'Najpekniejsze miejsca w Polsce',
        image_url: './assets/01.png',
        price: 1000,
        seats: 120,
        rating: 0,
    },
    {
        id : 1,
        name: 'Podróż po Polsce',
        country: 'Polska',
        startDate: add(new Date(), { months: 3 }),
        endDate: add(new Date(), { months: 4 }),
        description: 'Najpekniejsze miejsca w Polsce',
        image_url: './assets/01.png',
        price: 150,
        seats: 50,
        rating: 0,
    },
    {
        id : 2,
        name: 'Podróż po Polsce',
        country: 'Polska',
        startDate: add(new Date(), { months: 4 }),
        endDate: add(new Date(), { months: 5 }),
        description: 'Najpekniejsze miejsca w Polsce',
        image_url: './assets/01.png',
        price: 970,
        seats: 40,
        rating: 0,
    },
    {
        id : 3,
        name: 'Podróż po Niemczech',
        country: 'Niemcy',
        startDate: add(new Date(), { months: 2 }),
        endDate: add(new Date(), { months: 3 }),
        description: 'Najpekniejsze miejsca w Niemczech',
        image_url: './assets/02.svg',
        price: 1300,
        seats: 30,
        rating: 0,
    },
    {
        id : 4,
        name: 'Podróż po Niemczech',
        country: 'Niemcy',
        startDate: add(new Date(), { months: 3 }),
        endDate: add(new Date(), { months: 4 }),
        description: 'Najpekniejsze miejsca w Niemczech',
        image_url: './assets/02.svg',
        price: 1600,
        seats: 15,
        rating: 0,
    },
    {
        id : 5,
        name: 'Podróż po Wlk. Brytanii',
        country: 'Wlk. Brytania',
        startDate: add(new Date(), { months: 2 }),
        endDate: add(new Date(), { months: 3 }),
        description: 'Najpekniejsze miejsca w Wlk. Brytanii',
        image_url: './assets/03.png',
        price: 2000,
        seats: 35,
        rating: 0,
    },
    {
        id : 6,
        name: 'Podróż po Hiszpanii',
        country: 'Hiszpania',
        startDate: add(new Date(), { months: 2 }),
        endDate: add(new Date(), { months: 3 }),
        description: 'Najpekniejsze miejsca w Hiszpanii',
        image_url: './assets/04.svg',
        price: 2200,
        seats: 30,
        rating: 0,
    },
    {
        id : 7,
        name: 'Podróż po Hiszpanii',
        country: 'Hiszpania',
        startDate: add(new Date(), { months: 2 }),
        endDate: add(new Date(), { months: 3 }),
        description: 'Najpekniejsze miejsca w Hiszpanii',
        image_url: './assets/04.svg',
        price: 2100,
        seats: 30,
        rating: 0,
    }
]